<?php

$title = '删除用户';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>确定要删除用户名为
    '<?php echo $this->escapeHtml($user->getName()); ?>' 密码为
    '<?php echo $this->escapeHtml($user->getPassword()); ?>'的用户?
</p>
<?php
$url = $this->url('user', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $user->getId(); ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>